### ISSUE TITLE
Problema en los detalles de un dataset

### ISSUE THREAD

**Issue by frafermot** [berenjena-hub/berenjena-hub#58]
Cuando despliego la aplicación en local situado en la rama "main" y abro Mozilla Firefox en la versión 132.0.1 y accedo a la vista detallada de un dataset ocurre lo siguiente:

- Error inesperado de carga de los ratings. 

![Captura desde 2024-12-06 13-47-36](https://github.com/user-attachments/assets/11470757-db6a-479e-ba51-d1e8f4e7b896)

Debido al mensaje de error no es posible realizar los tests de interfaz por lo que los relacionados con esta vista fallan.

**Comment by sheche1** [comment]
Para solucionar el error Unknown table 'uvlhubdb.webhook' que se producía al ejecutar la migración, eliminé la línea op.drop_table('webhook') del archivo de migración 9c9c1d6260de_crear_tabla_ratings.py, dado que esa tabla no existía en la base de datos. De esta forma, al ejecutar flask db upgrade nuevamente, la migración se completó con éxito sin intentar eliminar una tabla inexistente.
Se utilizó rosemary db:reset para restablecer la base de datos a un estado limpio, seguido de rosemary db:migrate para aplicar todas las migraciones pendientes y así asegurar que la estructura de la base de datos estuviera actualizada. Finalmente, se ejecutó rosemary db:seed para poblar la base de datos con datos iniciales de prueba, dejando el entorno listo para continuar el desarrollo.

los comandos:
rosemary db:reset
rosemary db:migrate
rosemary db:migrate
